### ISSUE TITLE
Using the polyp dataset, run train_ hourglass. py, DSC is always kept at a value of -0.0032

### ISSUE THREAD

**Issue by CTGUzhangguangyi** [marinbenc/medical-polar-training#2]
Using the polyp dataset, run train_ hourglass. py, DSC is always kept at a value of -0.0032. How can I solve this problem.

**Comment by marinbenc** [comment]
Hello, the stacked hourglass network does not use the Dice coefficient as a metric, so I'm not really sure what the problem is, unless I misunderstood your question. The stacked hourglass uses the MSE from each stack's heatmap compared to the GT heatmap, as defined here:

https://github.com/marinbenc/medical-polar-training/blob/91f9540a07dc63138faa23c36031236d4e616b8c/models/stacked_hourglass/stacked_hourglass.py#L19
